name: macOS

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          setup-python: 'false'
          version: 6.4.3
          modules: qtwebengine

      - name: Build kleiner-brauhelfer-2
        run: |
          chmod +x ./build_macos.sh
          ./build_macos.sh "${Qt6_DIR}/bin/" "-${{ github.sha }}"
          mkdir deploy
          cp build-macos/bin/kbh2_*.zip deploy/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: kleiner-brauhelfer-2
          path: deploy
